{
 "title": "Kubebench Workflow Dashboard",
 "time": { "from": "2018-10-16T12:17:13.501Z", "to": "2018-10-16T12:20:46.493Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "workflow",
    "label": "Workflow",
    "query": "label_values(kube_pod_labels{namespace=~\"$namespace\"}, label_workflows_argoproj_io_workflow)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=~\"$workflow-.*\", container_name=\"main\", container_name!=\"POD\"})",
     "legendFormat": "Workflow: $workflow"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"$workflow-.*\"}[1m] ) )",
     "legendFormat": "Workflow: $workflow"
    }
   ]
  },
  {
   "title": "Disk IOs per Workflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_disk_read_time_ms{namespace=\"$namespace\", pod=~\"$workflow-.*\"}",
     "legendFormat": "Workflow: $workflow"
    },
    {
     "expr": "node_disk_write_time_ms{namespace=\"$namespace\", pod=~\"$workflow-.*\"}",
     "legendFormat": "Workflow: $workflow"
    }
   ]
  }
 ]
}