# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  - app_dir: kubeflow/kubebench/test/workflows
    component: workflows
    name: kubebench-e2e

