# System basics
platform: 'workstation'
platform_type: 'custom'

# reporting
report_auth: 'my_report_auth.json'
report_project: 'my_report_project'
report_dataset: 'my_report_dataset'
report_table: 'my_report_table'

# tf-cnn-benchmarks
tf_cnn_bench_configs:
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/aws_cpu_r4.8xlarge.yaml
