kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: kubebench-operator
  name: controller

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubebench-operator
rules:
- apiGroups:
  - kubebench.operator
  resources:
  - kubebenchjobs.kubebench.operator
  - kubebenchjobs
  verbs:
  - create
  - update
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - create
  - update
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - get
  - list

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubebench-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubebench-operator
subjects:
- kind: ServiceAccount
  name: controller
  namespace: kubebench-operator

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: kubebench-operator
  name: controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccount: controller
      volumes:
      - name: config
        secret:
          secretName: config
      containers:
      - name: controller
        image: #CUSTOM IMAGE HERE
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
