#uncomment lines
apiVersion: kubebench.operator/v1
kind: KubebenchJob
metadata:
  name: kubebench-job
  namespace: default
spec:
  serviceAccount: default
  volumeSpecs:
    configVolume:
      name: my-config-volume
      persistentVolumeClaim:
        claimName: kubebench-config-pvc
    experimentVolume:
      name: my-experiment-volume
      persistentVolumeClaim:
        claimName: kubebench-exp-pvc
  # secretSpecs: # optional
  #   githubTokenSecret: # optional
  #     secretName: my-github-token-secret
  #     secretKey: my-github-token-secret-key
  #   gcpCredentialsSecret: # optional
  #     secretName: my-gcp-credentials-secret
  #     secretKey: my-gcp-credentials-secret-key
  jobSpecs:
    preJob: # optional
      container: # optional between "container" and "resource"
        name: my-prejob
        image: gcr.io/myprejob-image:latest # change it before using
    mainJob: # mandatory
      resource: # optional between "container" and "resource"
        manifestTemplate:
          valueFrom:
            ksonnet: # optional, more types in the future
              name: kubebench-example-tfcnn-with-monitoring
              package: kubebench-examples
              registry: /kubebench/config/registry/kubebench
        manifestParameters:
          valueFrom:
            path: tf-cnn/tf-cnn-dummy.yaml
        createSuccessCondition: createSuccess # optional
        createFailureCondition: createFailure # optional
        runSuccessCondition: runSuccess # optional
        runFailureCondition: runFailure # optional
        #other optional fields: "manifest" - string of raw manifest
    postJob: # optional
      container: # optional between "container" and "resource"
        name: my-postjob
        image: gcr.io/kubeflow-images-public/kubebench/kubebench-example-tf-cnn-post-processor:3c75b50
  reportSpecs: # optional
    csv: # optional
        - inputPath: result.json
          outputPath: report.csv