name: tf-cnn-dummy
args: null
image: gcr.io/kubeflow-images-public/kubebench/kubebench-example-tf-cnn-runner-cpu:v0.4.0-13-g262c593
num_worker: 1
num_ps: 0
batch_size: 2
num_batches: 20
model: resnet50
variable_update: parameter_server
num_gpus: 1
local_parameter_device: cpu
device: cpu
data_format: NHWC
forward_only: true
