{
 "title": "Kubebench Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\", label_monitoring=\"kubebench-prometheus\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by (pod_name)( rate(container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"$pod\", container_name!=\"POD\"}[1m]) ))\n"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device=\"tmpfs\"}) - sum(node_filesystem_free_bytes{device=\"tmpfs\"}) ) / sum(node_filesystem_size_bytes{device=\"tmpfs\"}) * 100"
    }
   ]
  },
  {
   "title": "POD memory usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{image!=\"\", namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"POD\"})",
     "legendFormat": "Pod name: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)( rate(container_cpu_usage_seconds_total{container_name!=\"POD\", image!=\"\",pod_name=~\"$pod\"}[1m] ) )",
     "legendFormat": "Pod name: {{pod_name}}"
    }
   ]
  },
  {
   "title": "Disk IOs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_disk_io_now", "legendFormat": "Device: {{device}}" }
   ]
  }
 ]
}