#uncomment lines
apiVersion: kubebench.operator/v1
kind: KubebenchJob
metadata:
  name: kubebench-job
  namespace: default
spec:
  serviceAccount: default
  volumeSpecs:
    configVolume:
      name: my-config-volume
      persistentVolumeClaim:
        claimName: kubebench-config-pvc
    experimentVolume:
      name: my-experiment-volume
      persistentVolumeClaim:
        claimName: kubebench-exp-pvc
  # secretSpecs: # optional
  #   githubTokenSecret: # optional
  #     secretName: my-github-token-secret
  #     secretKey: my-github-token-secret-key
  #   gcpCredentialsSecret: # optional
  #     secretName: my-gcp-credentials-secret
  #     secretKey: my-gcp-credentials-secret-key
  jobSpecs:
    # preJob: # optional
    #   container: # optional between "container" and "resource"
    #     name: my-prejob
    #     image: gcr.io/myprejob-image:latest
    mainJob: # mandatory
      resource: # optional between "container" and "resource"
        manifestTemplate:
          valueFrom:
            ksonnet: # optional, more types in the future
              prototype: kubebench-example-tfcnn
              package: kubebench-examples
              registry: github.com/kubeflow/kubebench/tree/master/kubebench
        manifestParameters:
          valueFrom:
            path: abc/def/ghi.yaml
        # createSuccessCondition: # optional
        # createFailureCondition: # optional
        # runSuccessCondition: # optional
        # runFailureCondition: # optional
        # other optional fields: "manifest" - string of raw manifest
    postJob: # optional
      container: # optional between "container" and "resource"
        name: my-postjob
        image: gcr.io/kubeflow-images-public/kubebench/kubebench-example-tf-cnn-post-processor:3c75b50
  reportSpecs: # optional
    csv: # optional, more types in the future
        - inputPath: result.json
          outputPath: report.csv