---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubebench-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: "/var/nfs/kubebench"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubebench-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Mi
