apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-job-
spec:
  entrypoint: main
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: kubebench-runner-pvc

  templates:
  - name: main
    steps:
    - - name: generate-config
        template: configurator
        arguments:
          parameters:
          - name: config-file
            value: /configurator/tf_cnn_config.yaml
          - name: output-file
            value: /configurator/out.json
    - - name: run-benchmark
        template: runner
        arguments:
          parameters:
          - name: k8manifest
            value: "{{steps.generate-config.outputs.parameters.out-file}}"

  - name: configurator
    inputs:
      parameters:
      - name: config-file
      - name: output-file
    container:
      image: localhost:5000/configurator
      args: ["--config-file={{inputs.parameters.config-file}}", "--output-file={{inputs.parameters.output-file}}"]
      volumeMounts:
      - mountPath: /configurator
        name: task-pv-storage
    outputs:
      parameters:
      - name: out-file
        valueFrom:
          path: /configurator/out.json

  - name: runner
    inputs:
      parameters:
      - name: k8manifest
    resource:
      action: apply
      successCondition: status.phase == Done
      failureCondition: status.phase == Failed
      manifest: |
        {{inputs.parameters.k8manifest}}

  - name: reporter
    inputs:
      parameters:
      - name: log-files-dir
      - name: output-file
    container:
      image: localhost:5000/reporter
      args: ["--files-path={{inputs.parameters.log-files-dir}}", "--output-file={{inputs.parameters.output-file}}"]
      volumeMounts:
      - mountPath: /reporter
        name: task-pv-storage
    outputs:
      parameters:
      - name: out-file
        valueFrom:
          path: /reporter/result.csv
